Timer fixes
parallel-runtimes/lomp pull request #30
Opened 2021-08-04 10:45 UTC by JimCownie

Enhancements to add the ability to run some of the load/store measurements across all combinations of source and target.
Minor tweak to `plot.py` to split the title of a plot over two lines if it is too long for one.

2021-08-06 09:06 UTC, mjklemm commented
Can you please include a summary of the changes of the TimerFixes branch in this pull request?

2021-08-06 10:03 UTC, JimCownie commented
I just pushed a commit which fixed one minor issue (missing info on the help in atomics.cc), and added a more general description of the changes. Is that what you wanted?

2021-08-06 10:16 UTC, mjklemm commented
I was talking about CHANGELOG.md

2021-08-07 06:46 UTC, mjklemm commented
There's only a very minor change that I have suggested?  Can you accept it into the PR, please?

2021-08-07 06:46 UTC, mjklemm requested changes

2021-08-07 06:46 UTC, mjklemm commented on microBM/atomics.cc
> +         "I[ifet]      -- Atomic increment of integer or float\n"
```suggestion
         "I[ifet]      -- Atomic increment of integer (i) or float (f)\n"
```

2021-08-07 06:47 UTC, merged