Fix compilation issues
parallel-runtimes/lomp pull request #60
Opened 2022-08-18 18:48 UTC by save-buffer

Hi! First I just wanted to say I loved the book - read it from cover to cover and learned a ton!

I just cloned the runtime and tried to build it and ran into a few compilation issues. I first compiled with GCC and fixed up those compilation issues, but then ran into linker errors with libgomp (libgomp is just broken on my version of GCC as far as I can tell...), so I switched to clang, and fixed up the compilation errors there. 

Also I fixed a couple of typos in the python script. I'm not able to run the examples and also `runLocks.py`.

2022-08-22 14:49 UTC, mjklemm requested changes
Thanks for your PR request.  There's only one small thing.

2022-08-22 14:49 UTC, mjklemm commented on src/target_x86_64.h
> +#include <immintrin.h>
This should not be needed, as the `__rdtsc()` should be coming from `x86intrin.h`.  

So, if `_mm_pause` is causing the issue, the proper header should be `emmintrin.h`.

2022-08-23 17:22 UTC, save-buffer commented on src/target_x86_64.h
> +#include <immintrin.h>
It seems it was an issue with `xabort`'s declaration, which the intel intrinsics guide said was in immintrin.

```
/home/sasha/projects/lomp/src/locks.cc: In member function 'bool lomp::locks::speculativeLock<baseLockType>::try_lock()':
/home/sasha/projects/lomp/src/target_x86_64.h:84:38: error: there are no arguments to '_xabort' that depend on a template parameter, so a declaration of '_xabort' must be available [-fpermissive]
   84 | #define Target_AbortSpeculation(tag) _xabort(tag)
      |                                      ^~~~~~~
/home/sasha/projects/lomp/src/locks.cc:299:9: note: in expansion of macro 'Target_AbortSpeculation'
  299 |         Target_AbortSpeculation(0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/home/sasha/projects/lomp/src/target_x86_64.h:84:38: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
   84 | #define Target_AbortSpeculation(tag) _xabort(tag)
      |                                      ^~~~~~~
/home/sasha/projects/lomp/src/locks.cc:299:9: note: in expansion of macro 'Target_AbortSpeculation'
  299 |         Target_AbortSpeculation(0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
  ```
  
It seems like switching it to `<rtmintrin.h>` works too, if that's better. We could also only include it if we're not compiling with clang (similar to the `Target::` thing)

2022-08-24 06:01 UTC, mjklemm commented
Ah, right.  `_xabort()` is the culprit.  Can you please use the minimal header?  Thanks!

2022-08-24 06:04 UTC, mjklemm commented on src/target_x86_64.h
> +#endif
I think this can go back to be `#define Target_AbortSpeculation(tag) _xabort(tag)` for both GCC and clang.  If the `_xabort` is not defined, then this code should not be active.  If it is, the problem lies elsewhere in the code.

2022-08-24 06:08 UTC, mjklemm approved these changes
This should now do it.

2022-08-24 06:09 UTC, mjklemm commented
Many thanks for your contribution!

2022-08-24 06:09 UTC, merged